--script créa° BDD PostgreSQL, généré depuis entité Doctrine du projet
--stack=symfony8 et postgresql 14/ Doctrine ORM
--usage-> psql -U postgres -d vite_et_gourmand2 -f schema.sql

--table plat (entrée plat dessert)
CREATE TABLE plat (
    id          INT          GENERATED BY DEFAULT AS IDENTITY NOT NULL,    
    nom         VARCHAR(100) NOT NULL,
    type        VARCHAR(50)  NOT NULL,
    description TEXT         DEFAULT NULL,
    PRIMARY KEY (id)
);

--table allergène (allergènes majeurs règlmnta° UE), many to many car allergène peut être dans plusieurs plat
CREATE TABLE allergene (
    id  INT          GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nom VARCHAR(100) NOT NULL,
    PRIMARY KEY (id)
);

--table newsletter (incriotion et mail liste brevo)
CREATE TABLE newsletter (
    id               INT          GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email            VARCHAR(180) NOT NULL,
    date_inscription TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    PRIMARY KEY (id)
);

--table user (utilisaters de l'appli->clients, employés, admin)
--rôle stockés en json : ["ROLE_USER"], ["ROLE_EMPLOYE"], ["ROLE_ADMIN"]
--actif=false->compte desac par admin dc connex° refusée
CREATE TABLE "user" (
    id            INT          GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email         VARCHAR(180)  NOT NULL,
    roles         JSON          NOT NULL,
    password      VARCHAR(255)  NOT NULL,
    nom           VARCHAR(50)   NOT NULL,
    prenom        VARCHAR(50)   NOT NULL,
    gsm           VARCHAR(20)   DEFAULT NULL,
    adresse       VARCHAR(255)  DEFAULT NULL,
    ville         VARCHAR(100)  DEFAULT NULL,,
    code_postal   VARCHAR(10)   DEFAULT NULL,,
    actif         BOOLEAN       NOT NULL,
    PRIMARY KEY (id)
);

--index unique sur email, identifiant de connexion
CREATE UNIQUE INDEX UNIQ_8D93D649E7927C74 ON "user" (email);

--table contact, msg recu via formulaire, sauvegarde bdd+notif mail brevo
CREATE TABLE contact (
    id          INT          GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    titre       VARCHAR(150) NOT NULL,
    description TEXT         NOT NULL,
    email       VARCHAR(180) NOT NULL,
    date        TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    PRIMARY KEY (id)
);

--table horaire, ouverture/jour,heure 00:00/00:00->fermé ce jour, modif° w/ espace employé
CREATE TABLE horaire (
    id              INT          GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    jour            VARCHAR(15)  NOT NULL,
    heure_ouverture TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    heure_fermeture TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    PRIMARY KEY (id)
);

--table menu, actif=false->menu masqué s/ site, filtrable par thème,régime & prix
CREATE TABLE menu (
    id                   INT            GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    titre                VARCHAR(100)   NOT NULL,
    description          TEXT           DEFAULT NULL,
    theme                VARCHAR(50)    DEFAULT NULL,
    regime               VARCHAR(50)    DEFAULT NULL,
    nb_personnes_min     INT            NOT NULL,
    prix                 NUMERIC(10,2)  NOT NULL,
    stock                INT            NOT NULL,
    conditions           TEXT           DEFAULT NULL,
    actif                BOOLEAN        NOT NULL,
    PRIMARY KEY (id)
);

--table image menu, photo associé à un menu (relation manytoone) et url->chemin relatif depuis/ public/images/menus/
CREATE TABLE image_menu (
    id      INT          GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    url     VARCHAR(255) NOT NULL,
    menu_id INT          NOT NULL,
    PRIMARY KEY (id)
);

CREATE INDEX IDX_8F3FD00DCCD7E912 ON image_menu (menu_id);

--table commande
CREATE TABLE commande (
    id                  INT            GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    numero_commande     VARCHAR(50)    NOT NULL,
    date_commande       TIMESTAMP(0)   WITHOUT TIME ZONE NOT NULL,
    date_prestation     DATE           NOT NULL,
    heure_livraison     TIME(0)        WITHOUT TIME ZONE NOT NULL,
    adresse_livraison   VARCHAR(255)   NOT NULL,
    ville_livraison     VARCHAR(100)   NOT NULL,
    nb_personnes        INT            NOT NULL,
    prix_menu           NUMERIC(10,2)  NOT NULL,
    prix_livraison      NUMERIC(10,2)  NOT NULL,
    prix total          NUMERIC(10,2)  NOT NULL,
    statut              VARCHAR(50)    NOT NULL,
    pret_materiel       BOOLEAN        NOT NULL,
    materiel_restitue   BOOLEAN        NOT NULL,
    utilisateur_id      INT            NOT NULL,
    menu_id             INT            NOT NULL,
    PRIMARY KEY (id)
);

CREATE INDEX IDX_6EEAA67DFB88E14F ON commande (utilisateur_id);
CREATE INDEX IDX_6EEAA67DCCD7E912 ON commande (menu_id);

--table avis, valide=false par défaut car valida° employé, onetoone w/ commande (1avis max/commande)
CREATE TABLE avis (
    id              INT       GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    note            INT       NOT NULL, 
    commentaire     TEXT      DEFAULT NULL, 
    valide          BOOLEAN   NOT NULL,
    date_avis       TIMESTAMP(0)  WITHOUT TIME ZONE NOT NULL,
    utilisateur_id  INT   NOT NULL,
    commande_id     INT   NOT NULL,
    PRIMARY KEY (id)
);

CREATE INDEX IDX_8F91ABF0FB88E14F ON avis (utilisateur_id);
--index unique->1avis/commande (OneToOne)
CREATE UNIQUE INDEX UNIQ_8F91ABF082EA2E54 ON avis (commande_id);

--table historique statut (changement statu et mode contact mail, gsm, sms...)
CREATE TABLE historique_statut (
    id            INT         GENERATED BY DEFAULT AS IDENTITY NOT NULL, 
    satut         VARCHAR(50) NOT NULL,
    date_heure    TIMESTAMP(0)  WITHOUT TIME ZONE NOT NULL,
    commentaire   TEXT        DEFAULT NULL,
    mode_contact  VARCHAR(50) DEFAULT NULL,
    commande_id   INT         NOT NULL,
    PRIMARY KEY (id)
);

CREATE INDEX IDX_2C2650E382EA2E54 ON historique_statut (commande_id);

--table reset password token (token réinitlsa° mdp)
--selector->partie publique ds url
--hashed_token->hash SHA-256 du token secret (jamais clair)
--expires_at->expiration ap 1h
CREATE TABLE reset_password_token (
    id              INT            GENERATED BY DEFAULT AS IDENTITY NOT NULL, 
    selector        VARCHAR(20)    NOT NULL,
    hashed_token    VARCHAR(100)   NOT NULL,
    expires_at      TIMESTAMP(0)  WITHOUT TIME ZONE NOT NULL,
    utilisateur_id  INT            NOT NULL,
    PRIMARY KEY (id)
);

CREATE INDEX IDX_452C9EC5FB88E14F ON reset_password_token (utilisateur_id);

--table menu_plat, jointure manytomany entre menu et plat (menu contient plusieurs plat et plat peut être dans plusieurs menus)
CREATE TABLE menu_plats (
    menu_id INT NOT NULL,
    plat_id INT NOT NULL,,
    PRIMARY KEY (menu_id, plat_id)
);

CREATE INDEX IDX_E8775249CCD7E912 ON menu_plat (menu_id);
CREATE INDEX IDX_E8775249D73DB560 ON menu_plat (plat_id);

--table plat_ellergene, jointure manytomany entre plat et allergene(plat peut avoir plusieurs allergènes)
CREATE TABLE plat_allergene (
    plat_id      INT NOT NULL,
    allergene_id INT NOT NULL,
    PRIMARY KEY (plat_id, allergene_id)
);

CREATE INDEX IDX_6FA44BBFD73DB560 ON plat_allergene (plat_id);
CREATE INDEX IDX_6FA44BBF4646AB2  ON plat_allergene (allergene_id);

--table messenger message, table inter,e symfony messenger, pas utilisé ici mais crée automtqmnt par symfony)
CREATE TABLE messenger_messages (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    body         TEXT         NOT NULL,
    headers      TEXT         NOT NULL,
    queue_name   VARCHAR(190) NOT NULL,
    created_at   TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
    PRIMARY KEY (id)
);

CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750
    ON messenger_messages (queue_name, available_at, delivered_at, id);

--contraintes foreign keys, ajouté apr créa° de ttes les tables pr éviter erreur réfrces circulaire
-- plat_allergene->plat et allergene
ALTER TABLE plat_allergene
    ADD CONSTRAINT FK_6FA44BBFD73DB560
    FOREIGN KEY (plat_id) REFERENCES plat (id) ON DELETE CASCADE;

ALTER TABLE plat_allergene
    ADD CONSTRAINT FK_6FA44BBF4646AB2
    FOREIGN KEY (allergene_id) REFERENCES allergene (id) ON DELETE CASCADE;

-- avis->user et commande
ALTER TABLE avis
    ADD CONSTRAINT FK_8F91ABF0FB88E14F
    FOREIGN KEY (utilisateur_id) REFERENCES "user" (id);

ALTER TABLE avis
    ADD CONSTRAINT FK_8F91ABF082EA2E54
    FOREIGN KEY (commande_id) REFERENCES commande (id);

-- reset_password_token->user
ALTER TABLE reset_password_token
    ADD CONSTRAINT FK_452C9EC5FB88E14F
    FOREIGN KEY (utilisateur_id) REFERENCES "user" (id);

-- historique_statut->commande
ALTER TABLE historique_statut
    ADD CONSTRAINT FK_2C2650E382EA2E54
    FOREIGN KEY (commande_id) REFERENCES commande (id);

-- commande->user et menu
ALTER TABLE commande
    ADD CONSTRAINT FK_6EEAA67DFB88E14F
    FOREIGN KEY (utilisateur_id) REFERENCES "user" (id);

ALTER TABLE commande
    ADD CONSTRAINT FK_6EEAA67DCCD7E912
    FOREIGN KEY (menu_id) REFERENCES menu (id);

-- menu_plat->menu et plat
ALTER TABLE menu_plat
    ADD CONSTRAINT FK_E8775249CCD7E912
    FOREIGN KEY (menu_id) REFERENCES menu (id) ON DELETE CASCADE;

ALTER TABLE menu_plat
    ADD CONSTRAINT FK_E8775249D73DB560
    FOREIGN KEY (plat_id) REFERENCES plat (id) ON DELETE CASCADE;

-- image_menu->menu
ALTER TABLE image_menu
    ADD CONSTRAINT FK_8F3FD00DCCD7E912
    FOREIGN KEY (menu_id) REFERENCES menu (id);









