<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260718140517 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE image_menu (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, url VARCHAR(255) NOT NULL, menu_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8F3FD00DCCD7E912 ON image_menu (menu_id)');
        $this->addSql('CREATE TABLE menu_plat (menu_id INT NOT NULL, plat_id INT NOT NULL, PRIMARY KEY (menu_id, plat_id))');
        $this->addSql('CREATE INDEX IDX_E8775249CCD7E912 ON menu_plat (menu_id)');
        $this->addSql('CREATE INDEX IDX_E8775249D73DB560 ON menu_plat (plat_id)');
        $this->addSql('CREATE TABLE plat_allergene (plat_id INT NOT NULL, allergene_id INT NOT NULL, PRIMARY KEY (plat_id, allergene_id))');
        $this->addSql('CREATE INDEX IDX_6FA44BBFD73DB560 ON plat_allergene (plat_id)');
        $this->addSql('CREATE INDEX IDX_6FA44BBF4646AB2 ON plat_allergene (allergene_id)');
        $this->addSql('ALTER TABLE image_menu ADD CONSTRAINT FK_8F3FD00DCCD7E912 FOREIGN KEY (menu_id) REFERENCES menu (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE menu_plat ADD CONSTRAINT FK_E8775249CCD7E912 FOREIGN KEY (menu_id) REFERENCES menu (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE menu_plat ADD CONSTRAINT FK_E8775249D73DB560 FOREIGN KEY (plat_id) REFERENCES plat (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE plat_allergene ADD CONSTRAINT FK_6FA44BBFD73DB560 FOREIGN KEY (plat_id) REFERENCES plat (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE plat_allergene ADD CONSTRAINT FK_6FA44BBF4646AB2 FOREIGN KEY (allergene_id) REFERENCES allergene (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE image_menu DROP CONSTRAINT FK_8F3FD00DCCD7E912');
        $this->addSql('ALTER TABLE menu_plat DROP CONSTRAINT FK_E8775249CCD7E912');
        $this->addSql('ALTER TABLE menu_plat DROP CONSTRAINT FK_E8775249D73DB560');
        $this->addSql('ALTER TABLE plat_allergene DROP CONSTRAINT FK_6FA44BBFD73DB560');
        $this->addSql('ALTER TABLE plat_allergene DROP CONSTRAINT FK_6FA44BBF4646AB2');
        $this->addSql('DROP TABLE image_menu');
        $this->addSql('DROP TABLE menu_plat');
        $this->addSql('DROP TABLE plat_allergene');
    }
}
