<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260718143221 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE commande (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, numero_commande VARCHAR(50) NOT NULL, date_commande TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, date_prestation DATE NOT NULL, heure_livraison TIME(0) WITHOUT TIME ZONE NOT NULL, adresse_livraison VARCHAR(255) NOT NULL, ville_livraison VARCHAR(100) NOT NULL, nb_personnes INT NOT NULL, prix_menu NUMERIC(10, 2) NOT NULL, prix_livraison NUMERIC(10, 2) NOT NULL, prix_total NUMERIC(10, 2) NOT NULL, statut VARCHAR(50) NOT NULL, pret_materiel BOOLEAN NOT NULL, materiel_restitue BOOLEAN NOT NULL, utilisateur_id INT NOT NULL, menu_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6EEAA67DFB88E14F ON commande (utilisateur_id)');
        $this->addSql('CREATE INDEX IDX_6EEAA67DCCD7E912 ON commande (menu_id)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, nom VARCHAR(50) NOT NULL, prenom VARCHAR(50) NOT NULL, gsm VARCHAR(20) DEFAULT NULL, adresse VARCHAR(255) DEFAULT NULL, ville VARCHAR(100) DEFAULT NULL, code_postal VARCHAR(10) DEFAULT NULL, actif BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email)');
        $this->addSql('ALTER TABLE commande ADD CONSTRAINT FK_6EEAA67DFB88E14F FOREIGN KEY (utilisateur_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE commande ADD CONSTRAINT FK_6EEAA67DCCD7E912 FOREIGN KEY (menu_id) REFERENCES menu (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE commande DROP CONSTRAINT FK_6EEAA67DFB88E14F');
        $this->addSql('ALTER TABLE commande DROP CONSTRAINT FK_6EEAA67DCCD7E912');
        $this->addSql('DROP TABLE commande');
        $this->addSql('DROP TABLE "user"');
    }
}
