<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260718144931 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE historique_statut (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, statut VARCHAR(50) NOT NULL, date_heure TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, commentaire TEXT DEFAULT NULL, mode_contact VARCHAR(50) DEFAULT NULL, commande_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_2C2650E382EA2E54 ON historique_statut (commande_id)');
        $this->addSql('ALTER TABLE historique_statut ADD CONSTRAINT FK_2C2650E382EA2E54 FOREIGN KEY (commande_id) REFERENCES commande (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE historique_statut DROP CONSTRAINT FK_2C2650E382EA2E54');
        $this->addSql('DROP TABLE historique_statut');
    }
}
