services:
    #config° par défaut des services
    _defaults:
        autowire: true
        autoconfigure: true

    #enregistremnt ts les services dans src/
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    #UserChecker vérif si compte actif pr connexion, symfony call automatqmnt pdt chaque authentification
    App\EventListener\UserCheckerListener:
        tags:
            - { name: security.user_checker }
